#Configuration Server
server:
  port: 8081
  servlet:
    context-path: /teste-java
    encoding.charset: UTF-8
    encoding.force-response: true

#Configuration application
spring:
  application:
    name: Teste Java
